### PR TITLE
Adding Emailed into OperationEnum

### PR DESCRIPTION
**Pull request by mariodelabarra**
Adding Emailed into OperationEnum that it is used by the following entites:

- Estimate
- Invoice
- Payment
- SalesReceipt
- CreditMemo
- RefundReceipt
- PurchaseOrder

### CODE REVIEW

**Comment by clement911** [comment]
This file is generated from the XSD file so I cannot just accept manual edits to this file otherwise they will get reverted the next time the file is generated.

See https://developer.intuit.com/app/developer/qbo/docs/learn/explore-the-quickbooks-online-api/minor-versions

Currently QuickBooksSharp uses version 3.56
Was this field added in a more recent version of the XSD? 
If so, the new XSDs need to be added to the solution and the file must be regenerated.

**Comment by clement911** [comment]
I had a look at the latest XSD and I cannot see an 'emailed' value.
Is this documented in the API? If so, Intuit should have updated the XSDs accordingly.

**Comment by mariodelabarra** [comment]
I had configure Webhook in my application, and I notice that sometimes that I try to deserialize the [EntityChange](https://github.com/better-reports/QuickBooksSharp/blob/master/QuickBooksSharp/Webhooks/EntityChange.cs) entity I receive an exception when the Operation property has the value of "Emailed". What is weird is that I couldn't find any documentation related to this type of operation, there are just questions that other users did.

But you can find the configuration for receive the Emailed notification when you enter in the Dashboard/Webhooks of your application

image

**Comment by clement911** [comment]
It doesn't appear in the xsd. See https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/5b4edc68aa5eef6396ffcf155a347f80768e3414/IPPDotNetDevKitCSV3/Tools/XsdExtension/Intuit.Ipp.XsdExtension/Schema/IntuitRestServiceDef.xsd#L452

Neither does it appear in the official .NET library object. Open https://raw.githubusercontent.com/intuit/QuickBooks-V3-DotNET-SDK/5b4edc68aa5eef6396ffcf155a347f80768e3414/IPPDotNetDevKitCSV3/Tools/XsdExtension/Intuit.Ipp.Data/CDMEntities/Fms.cs and search for "enum OperationEnum".

Can you raise an issue with Intuit directly to fix their XSD? As I said, this enum is generated from the XSD. If it was a class, it could be made partial, but enums cannot be partial.

**Comment by clement911** [comment]
Closing since I haven't heard back but feel free to re-open.

**Pull request closed without merging**
